module.exports = {
  appId: "com.bluekaraoke.app",
  productName: "Blue Karaoke",
  executableName: "BlueKaraoke",
  publish: {
    provider: "github",
    owner: process.env.GH_OWNER || "SEU_USUARIO",
    repo: process.env.GH_REPO || "blue-karaoke",
    vPrefixedTagName: true,
  },
  directories: {
    output: "release",
    buildResources: "build",
  },
  files: [
    "electron/**/*",
    ".next/standalone/**/*",
    ".next/static/**/*",
    "public/**/*",
    "package.json",
    // Excluir pasta de vídeos baixados (apenas na raiz, não a API)
    "!musicas/**/*",
    "!musicas",
    "!db.sqlite",
    "!*.sqlite",
    "!**/*.map",
    "!**/node_modules/**/test/**",
    "!**/node_modules/**/tests/**",
    "!**/node_modules/**/*.md",
    "!**/node_modules/**/LICENSE*",
    "!**/node_modules/**/CHANGELOG*",
    "!**/node_modules/**/.github/**",
    "!**/drizzle-kit/**",
    "!**/drizzle.config.*",
    "!**/scripts/**",
    "!**/*.d.ts",
    "!drizzle/**",
    "!build/**",
    "!*.md",
    "!*.txt",
    "!test-*.js",
    "!node_modules/**",
  ],
  extraFiles: [],
  asar: false, // Desabilitar ASAR para evitar problemas com better-sqlite3
  win: {
    target: "nsis",
    icon: "public/icon.png",
    signAndEditExecutable: false,
    arch: ["x64", "ia32"],
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    perMachine: true,
    createDesktopShortcut: "always",
    createStartMenuShortcut: true,
  },
  forceCodeSigning: false,
  linux: {
    target: ["deb", "tar.gz"],
    icon: "public/icon.png",
    category: "AudioVideo",
  },
}
